### ISSUE TITLE
带端口号的源站地址是否不生效？

### ISSUE THREAD

**Issue by death4444** [webp-sh/halo-plugin-webp-cloud#11]
![image](https://github.com/user-attachments/assets/4cba305b-7bf1-4962-b160-f9ecd9a1ffea)
![image](https://github.com/user-attachments/assets/c408c2cb-6f56-47f9-8b28-dd8b6a069ea7)
![image](https://github.com/user-attachments/assets/03b35067-8537-4602-a193-79c77e642238)
![image](https://github.com/user-attachments/assets/923aba44-e320-4b43-a5bd-0072801d3780)

**Comment by ruibaby** [comment]
<img width="884" alt="image" src="https://github.com/user-attachments/assets/2867df0c-6f4a-454f-90f8-2d9a37f6c6e7">

和外部访问地址尾部的 / 有关，你需要保证这两个地址一致，因为目前相对路径的图片是需要判断完全相等，相关代码：

https://github.com/webp-sh/halo-plugin-webp-cloud/blob/b89915f79d1fc4caa53ec6d49052f9ad7778228f/src/main/java/se/webp/plugin/WebpCloudImageOptimizerWebFilter.java#L157

**Comment by death4444** [comment]
非常感谢指正，确实没想到由一个斜杠引发的血案，我已经自建服务搞定了。
