### ISSUE TITLE
halo最新版本没有生效

### ISSUE THREAD

**Issue by 907739769** [webp-sh/halo-plugin-webp-cloud#17]
halo最新版本没有生效

**Comment by JohnNiang** [comment]
Hi @907739769 , 需要等待 https://github.com/webp-sh/halo-plugin-webp-cloud/pull/15 合并并发布新版才能正常在 Halo 2.20.0 中使用。

**Comment by pengchangg** [comment]
![image](https://github.com/user-attachments/assets/bf975f78-195c-43ed-bf85-1cbb9381e0f7)
![image](https://github.com/user-attachments/assets/2a1363df-6f07-4a34-a905-37cb5141731e)
![image](https://github.com/user-attachments/assets/3a889e0a-f72a-48c1-9d3b-eed580899bd2)
最新版还是没有生效
