### ISSUE TITLE
最新版（2.20.4）没有生效

### ISSUE THREAD

**Issue by pengchangg** [webp-sh/halo-plugin-webp-cloud#18]
![image](https://github.com/user-attachments/assets/bf975f78-195c-43ed-bf85-1cbb9381e0f7)
![image](https://github.com/user-attachments/assets/2a1363df-6f07-4a34-a905-37cb5141731e)
![image](https://github.com/user-attachments/assets/3a889e0a-f72a-48c1-9d3b-eed580899bd2)

**Comment by JohnNiang** [comment]
Hi @pengchangg , thank you for reaching out here!

 1. 需要确认一下 WebP Cloud Halo 插件的版本。
 2. 确认一下详细的配置是否正确，尤其是源站。
 
我发现你的站点部分图片是正确处理了。

**Comment by pengchangg** [comment]
我当时配置完了之后没有生效，第二天看的时候就生效了，不知道什么情况
