### ISSUE TITLE
使用插件后图片全部失效

### ISSUE THREAD

**Issue by acanyo** [webp-sh/halo-plugin-webp-cloud#19]
![image](https://github.com/user-attachments/assets/2da68c0e-c32a-4191-9f11-30332754b8f7)
<img width="510" alt="image" src="https://github.com/user-attachments/assets/acf206d4-5019-4922-82b4-989ca6d48611">
<img width="94" alt="image" src="https://github.com/user-attachments/assets/3e980b77-9ee9-4fb4-b6c3-3dded72c9d6b">
<img width="159" alt="image" src="https://github.com/user-attachments/assets/60c315fd-ebd1-45bb-a849-7f1132d06e2e">
头像这个应该用的是图床不应该生效啊

**Comment by JohnNiang** [comment]
Hi @acanyo , thank you for reaching out here!

建议清理一下缓存后试试，我这边看到的头像是正常的。制图图片中提到的访问图片是出现 500 的情况，可能需要 @n0vad3v 看看。

**Comment by acanyo** [comment]
> Hi @acanyo , thank you for reaching out here!
> 
> 建议清理一下缓存后试试，我这边看到的头像是正常的。制图图片中提到的访问图片是出现 500 的情况，可能需要 @n0vad3v 看看。

我给插件关掉了

**Comment by n0vad3v** [comment]
@JohnNiang 好像这里用户的意思是：「头像的图片地址使用了图床，不应该被插件替换为 WebP Cloud 的地址」 🤔

**Comment by JohnNiang** [comment]
我这边访问 WebP Cloud 侧的图片，结果如下所示：

```bash
> http https://1dff922.webp.ee/zz3hxO.webp\?type\=blog\&width\=1600

HTTP/1.1 500 Internal Server Error
CF-RAY: 8d6ea5123ee59529-LHR
Connection: keep-alive
Content-Length: 105
Content-Type: text/plain; charset=utf-8
Date: Wed, 23 Oct 2024 03:29:49 GMT
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=LCqsA8Hz2uYSaMoR2LoK2ZBfxdG2iL3JGeRbQxwzYTSPSZH%2Fg7%2B9AJX1UO18xyuj4y2zwqHrKUdkrDJkq6xQp2VcSjNgmxtnV6N2782Gr1cj0ppoR6U%2BC7zWO1e6izA%2FiKztP%2B4jAb8M9zZk8FQ%3D"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
access-control-allow-origin: *
alt-svc: h3=":443"; ma=86400
cf-cache-status: DYNAMIC
server-timing: cfL4;desc="?proto=TCP&rtt=234969&sent=5&recv=7&lost=0&retrans=0&sent_bytes=2828&recv_bytes=787&delivery_rate=17254&cwnd=107&unsent_bytes=0&cid=a5ff1bcbd0feb680&ts=1718&x=0"
x-powered-by: WebP Cloud Services (NUE)

Fetch remote image failed: Download: remote file is not image, remote returned [text/plain;charset=UTF-8]
```

我尝试访问源站图片，结果如下所示：

```bash
> http https://www.mmm.sd/zz3hxO.webp

HTTP/1.1 404 Not Found
CF-Cache-Status: BYPASS
CF-RAY: 8d6ea7d4fae9231a-HKG
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Content-Length: 212
Content-Type: application/problem+json
Date: Wed, 23 Oct 2024 03:31:40 GMT
Expires: 0
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=CPUK%2BK%2Bahdx4H5GLlglEy6Imrg1TMoXLnF4ukDQ%2B%2BiAG5A0P8onVK7LdEk8jO1mLR7Hb%2Fq1avxM1wKW%2B4%2B9%2F5kUiHX2zJWRkxftqgOc5oWF%2BuINOpKeI%2BQiZsMpZ"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Set-Cookie: p_uv_id=fecf54de846fec2d3ea2483669eff820; path=/; expires=Wed, 23-Oct-24 16:00:00 GMT; HttpOnly
Strict-Transport-Security: max-age=31536000
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0
alt-svc: h3=":443"; ma=86400
server-timing: cfL4;desc="?proto=TCP&rtt=202379&sent=5&recv=6&lost=0&retrans=0&sent_bytes=2822&recv_bytes=761&delivery_rate=20798&cwnd=33&unsent_bytes=0&cid=8618c8796e853564&ts=262&x=0"

{
    "detail": "No static resource zz3hxO.webp.",
    "instance": "https://zja.icu/zz3hxO.webp",
    "requestId": "db791053-1561",
    "status": 404,
    "timestamp": "2024-10-23T03:31:40.981177464Z",
    "title": "Not Found",
    "type": "about:blank"
}
```

不是很清楚为什么返回的结果中的 instance 中的域名竟然是 `zja.icu`，实际请求的域名却是 `mmm.sd`。

**Comment by acanyo** [comment]
> 我这边访问 WebP Cloud 侧的图片，结果如下所示：
> 
> ```shell
> > http https://1dff922.webp.ee/zz3hxO.webp\?type\=blog\&width\=1600
> 
> HTTP/1.1 500 Internal Server Error
> CF-RAY: 8d6ea5123ee59529-LHR
> Connection: keep-alive
> Content-Length: 105
> Content-Type: text/plain; charset=utf-8
> Date: Wed, 23 Oct 2024 03:29:49 GMT
> NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
> Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=LCqsA8Hz2uYSaMoR2LoK2ZBfxdG2iL3JGeRbQxwzYTSPSZH%2Fg7%2B9AJX1UO18xyuj4y2zwqHrKUdkrDJkq6xQp2VcSjNgmxtnV6N2782Gr1cj0ppoR6U%2BC7zWO1e6izA%2FiKztP%2B4jAb8M9zZk8FQ%3D"}],"group":"cf-nel","max_age":604800}
> Server: cloudflare
> access-control-allow-origin: *
> alt-svc: h3=":443"; ma=86400
> cf-cache-status: DYNAMIC
> server-timing: cfL4;desc="?proto=TCP&rtt=234969&sent=5&recv=7&lost=0&retrans=0&sent_bytes=2828&recv_bytes=787&delivery_rate=17254&cwnd=107&unsent_bytes=0&cid=a5ff1bcbd0feb680&ts=1718&x=0"
> x-powered-by: WebP Cloud Services (NUE)
> 
> Fetch remote image failed: Download: remote file is not image, remote returned [text/plain;charset=UTF-8]> http https://1dff922.webp.ee/zz3hxO.webp\?type\=blog\&width\=1600 HTTP/1.1 500 Internal Server Error CF-RAY: 8d6ea5123ee59529-LHR Connection: keep-alive Content-Length: 105 Content-Type: text/plain; charset=utf-8 Date：Wed, 23 Oct 2024 03:29:49 GMT NEL: {"success_fraction":0, "report_to": "cf-nel", "max_age":604800}Report-To: {"endpoints":[{"url": "https:\/\/a.nel.cloudflare.com\/report\/v4?s=LCqsA8Hz2uYSaMoR2LoK2ZBfxdG2iL3JGeRbQxwzYTSPSZH%2Fg7%2B9AJX1UO18xyuj4y2zwqHrKUdkrDJkq6xQp2VcSjNgmxtnV6N2782Gr1cj0ppoR6U%2BC7zWO1e6izA%2FiKztP%2B4jAb8M9zZk8FQ%3D"}], "group"："cf-nel", "max_age":604800} 服务器: cloudflare access-control-allow-origin：* alt-svc: h3=":443"; ma=86400 cf-cache-status：DYNAMIC server-timing: cfL4;desc="?proto=TCP&rtt=234969&sent=5&recv=7&lost=0&retrans=0&sent_bytes=2828&recv_bytes=787&delivery_rate=17254&cwnd=107&unsent_bytes=0&cid=a5ff1bcbd0feb680&ts=1718&x=0" x-powered-by: WebP Cloud Services (NUE) Fetch remote image failed：下载：远程文件不是图像，远程返回 [text/plain;charset=UTF-8]
> ```
> 
> 我尝试访问源站图片，结果如下所示：
> 
> ```shell
> > http https://www.mmm.sd/zz3hxO.webp
> 
> HTTP/1.1 404 Not Found
> CF-Cache-Status: BYPASS
> CF-RAY: 8d6ea7d4fae9231a-HKG
> Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> Connection: keep-alive
> Content-Length: 212
> Content-Type: application/problem+json
> Date: Wed, 23 Oct 2024 03:31:40 GMT
> Expires: 0
> NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
> Pragma: no-cache
> Referrer-Policy: strict-origin-when-cross-origin
> Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=CPUK%2BK%2Bahdx4H5GLlglEy6Imrg1TMoXLnF4ukDQ%2B%2BiAG5A0P8onVK7LdEk8jO1mLR7Hb%2Fq1avxM1wKW%2B4%2B9%2F5kUiHX2zJWRkxftqgOc5oWF%2BuINOpKeI%2BQiZsMpZ"}],"group":"cf-nel","max_age":604800}
> Server: cloudflare
> Set-Cookie: p_uv_id=fecf54de846fec2d3ea2483669eff820; path=/; expires=Wed, 23-Oct-24 16:00:00 GMT; HttpOnly
> Strict-Transport-Security: max-age=31536000
> Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
> X-Content-Type-Options: nosniff
> X-Frame-Options: SAMEORIGIN
> X-XSS-Protection: 0
> alt-svc: h3=":443"; ma=86400
> server-timing: cfL4;desc="?proto=TCP&rtt=202379&sent=5&recv=6&lost=0&retrans=0&sent_bytes=2822&recv_bytes=761&delivery_rate=20798&cwnd=33&unsent_bytes=0&cid=8618c8796e853564&ts=262&x=0"
> 
> {
>     "detail": "No static resource zz3hxO.webp.",
>     "instance": "https://zja.icu/zz3hxO.webp",
>     "requestId": "db791053-1561",
>     "status": 404,
>     "timestamp": "2024-10-23T03:31:40.981177464Z",
>     "title": "Not Found",
>     "type": "about:blank"
> }> http https://www.mmm.sd/zz3hxO.webp HTTP/1.1 404 Not Found CF-Cache-Status：BYPASS CF-RAY: 8d6ea7d4fae9231a-HKG Cache-Control: no-cache, no-store, max-age=0, must-revalidate Connection: keep-alive Content-Length: 212 Content-Type: application/problem+json Date：Wed, 23 Oct 2024 03:31:40 GMT Expires：0 NEL: {"success_fraction":0, "report_to": "cf-nel", "max_age":604800} Pragma: no-cache Referrer-Policy: string-origin-when-cross-origin Report-To: {"endpoints":[{"url": "https:\/\a.nel.cloudflare.com\/report\/v4?s=CPUK%2BK%2Bahdx4H5GLlglEy6Imrg1TMoXLnF4ukDQ%2B%2BiAG5A0P8onVK7LdEk8jO1mLR7Hb%2Fq1avxM1wKW%2B4%2B9%2F5kUiHX2zJWRkxftqgOc5oWF%2BuINOpKeI%2BQiZsMpZ"}],"group":"cf-nel","max_age":604800} Server: cloudflare Set-Cookie: p_uv_id=fecf54de846fec2d3ea2483669eff820; path=/; expires=Wed, 23-Oct-24 16:00:00 GMT; HttpOnly Strict-Transport-Security: max-age=31536000 Vary：Access-Control-Request-Headers X-Content-Type-Options: nosniff X-Frame-Options：SAMEORIGIN X-XSS-Protection：0 alt-svc: h3=":443"; ma=86400 server-timing: cfL4;desc="?proto=TCP&rtt=202379&sent=5&recv=6&lost=0&retrans=0&sent_bytes=2822&recv_bytes=761&delivery_rate=20798&cwnd=33&unsent_bytes=0&cid=8618c8796e853564&ts=262&x=0" { "detail":"No static resource zz3hxO.webp.", "instance"："https://zja.icu/zz3hxO.webp", "requestId"："db791053-1561", "status"：404, "timestamp"："2024-10-23T03:31:40.981177464Z", "title":"未找到"，"类型"："about:blank" }
> ```
> 
> 不是很清楚为什么返回的结果中的 instance 中的域名竟然是 `zja.icu`，实际请求的域名却是 `mmm.sd`。
做了自定义域名转发,这个域名我也配置了但是不应该评论头像做了自定义域名转发,这个域名我也配置了但是不应该评论头像和图床的url不应该转发和图床的做了自定义域名转发,这个域名我也配置了但是不应该评论头像和图床的url不应该转发url不应该转发

**Comment by JohnNiang** [comment]
我们不推荐这样做。如果你确定要用 mmm.sd 域名，建议配置一下 Halo 的 external URL：`https://www.mmm.sd/`。否则 Halo 在解析当前请求的时候，不确定访问的是哪个域名，最终无法替换图片链接。

**Comment by acanyo** [comment]
好吧，用的CF的自定义域名转发 那关掉吧 这个issue
