### ISSUE TITLE
使用之后， 相对路径的图片绝对路径会错误

### ISSUE THREAD

**Issue by nukix** [webp-sh/halo-plugin-webp-cloud#5]
在 Markdown StackEdit 编辑器下我图片路径是 /upload/2022/09/e0c67b0c18cd421987077062bc738c7f.jpeg。

期望解析成：https://blog.uso6.com/upload/2022/09/e0c67b0c18cd421987077062bc738c7f.jpeg。

实际解析成：https://blog.uso6.com/archives/null/upload/2022/09/e0c67b0c18cd421987077062bc738c7f.jpeg。

导致图片找不到。

**Comment by nukix** [comment]
关掉 WebP Cloud Services 插件后就解析正确。

**Comment by ruibaby** [comment]
在 https://github.com/webp-sh/halo-plugin-webp-cloud/releases/tag/v1.1.0 中已修复。
