### ISSUE TITLE
安装配置后未生效

### ISSUE THREAD

**Issue by BoWang816** [webp-sh/halo-plugin-webp-cloud#6]
在后台配置好了代理地址，但是好像不生效
<img width="823" alt="image" src="https://github.com/webp-sh/halo-plugin-webp-cloud/assets/26587649/a3557da5-c5f6-4a65-bde1-86ceaef24c71">

原地址：https://nas.wangboweb.site:9300/
代理地址：https://79bdbee.webp.ee

并且通过代理地址访问图片也是可以的，但是通过原地址访问就代理不过去，可以帮忙看一下是怎么回事嘛

**Comment by kierankihn** [comment]
遇到了同样的问题：开启代理之后不起作用

站点地址：https://blog.kierankihn.com/ ，原图片服务器地址：https://r2.kierankihn.com/ ，代理地址：https://71a6a59.webp.ee/

以我的网站首页的背景图为例：原图片地址为 https://r2.kierankihn.com/blog/e0506c60f6442a6e8db69ba89ec62a08.png ，代理地址应为 https://71a6a59.webp.ee/blog/e0506c60f6442a6e8db69ba89ec62a08.png ，直接访问代理地址可以正常获取图片，但是在网站首页加载时 F12 可以发现请求的仍然为原图片地址

如图：

![image](https://github.com/webp-sh/halo-plugin-webp-cloud/assets/114803508/e35a6e13-37d7-49bf-9ca7-8869bf86edde)


halo 版本为 2.10，插件版本为 1.0.1

**Comment by kierankihn** [comment]
@ruibaby

**Comment by ruibaby** [comment]
目前的设计就是根据当前网站的域名进行替换，没有考虑到使用外部图源的情况。

或许需要一个图片源站的设置项。

**Comment by ruibaby** [comment]
https://github.com/webp-sh/halo-plugin-webp-cloud/releases/tag/v1.1.0 已支持配置多个代理地址。

**Comment by ruibaby** [comment]
我将关闭此 issue，后续如果有新版本的问题可以重新提交。
